#!/usr/bin/env node
// Build the game and, with --out, publish it into the site repo the way netmap is published:
//   frontend/public/casino/        the client (static files for Pages)
//   workers/casino/index.js        the Worker, bundled here so the site's CI uploads exactly
//                                  what was tested (its wrangler.toml sets no_bundle = true)
//   database/migrations/014_casino.sql   the D1 schema (never rewritten once it exists)
//
//   npm run build                       # dist/ only
//   npm run build -- --out ../j4den     # dist/ and the site repo

import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';

const args = process.argv.slice(2);
const outIdx = args.indexOf('--out');
const site = outIdx >= 0 ? resolve(args[outIdx + 1] ?? '') : null;
const root = process.cwd();
const dist = join(root, 'dist');
const bin = (n) => join(root, 'node_modules/.bin', n);
const env = { ...process.env, CASINO_API_ORIGIN: process.env.CASINO_API_ORIGIN ?? 'https://api.j4den.com' };

rmSync(dist, { recursive: true, force: true });
execFileSync(bin('vite'), ['build', '--config', 'client/vite.config.ts'], { stdio: 'inherit', env });
// wrangler writes the bundle next to the config when --outdir is relative, so pass it absolute.
execFileSync(bin('wrangler'), ['deploy', '--dry-run', '--outdir', join(dist, 'worker'), '-c', 'server/wrangler.toml'], { stdio: 'inherit', env });

if (!site) {
  console.log('\nbuilt dist/casino and dist/worker');
  process.exit(0);
}
if (!existsSync(join(site, 'frontend/public'))) {
  console.error(`--out ${site}: not the site repo (no frontend/public)`);
  process.exit(1);
}

const pub = join(site, 'frontend/public/casino');
rmSync(pub, { recursive: true, force: true });
cpSync(join(dist, 'casino'), pub, { recursive: true });

const wdir = join(site, 'workers/casino');
mkdirSync(wdir, { recursive: true });
cpSync(join(dist, 'worker/index.js'), join(wdir, 'index.js'));
writeFileSync(
  join(wdir, 'README.md'),
  '# workers/casino\n\nBuild output of [casino-simulator](https://github.com/JadenB9/casino-simulator): `index.js` is\n' +
    'generated by `npm run build -- --out <this repo>` there. Edit the source, not this file.\n' +
    '`wrangler.toml` (bindings, route) is maintained here.\n',
);

const mig = join(site, 'database/migrations/014_casino.sql');
const schema = readFileSync(join(root, 'server/migrations/0001_casino.sql'), 'utf8');
if (!existsSync(mig)) writeFileSync(mig, schema);
else if (readFileSync(mig, 'utf8') !== schema) console.warn('warning: 014_casino.sql in the site differs from server/migrations; migrations are append-only, add a new one');

console.log(`\npublished to ${site}: frontend/public/casino, workers/casino/index.js, database/migrations/014_casino.sql`);
